name: Add-In-Progress-Label-To-Tool-Request

on:
  issues:
    types: opened

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.comment.body, '/IVolunteerAsTribute') }}
        with:
          labels: In-Progress
