name: Alert-on-approval
on:
  issue_comment:
    types:
      - created
jobs:
  add-comment:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/approved') }}
    runs-on: ubuntu-latest
    steps:
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{github.event.pull_request.number}}
        body: "@Static-Flow"
