name: Tweet-New-Tool-Request
# This workflow is triggered when a label is added to an issue.
on:
  issues:
      types: [opened]
jobs:
    tweet:
      runs-on: ubuntu-latest
      steps:
        - uses: Eomm/why-don-t-you-tweet@v1
          with:
            tweet-message: "New tool request - ${{ github.event.issue.title }} -> ${{ github.event.issue.url }}"
          env:
            # Get your tokens from https://developer.twitter.com/apps
            TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
            TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
            TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
            TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
